name: CI-On-Dispatch

on: repository_dispatch

jobs:

  bump_ladybug_grasshopper:
    name: "Check Event"
    runs-on: ubuntu-latest
    if: github.event.action == 'ladybug_grasshopper_release'
    steps:
    - name: "Checkout Master Branch"
      uses: actions/checkout@v2
      with:
        ref: refs/heads/master
        token: ${{ secrets.DEPS_UPDATING }}
    - name: "Run Update Script"
      env:
        VERSION: ${{ github.event.client_payload.version }}
      run: |
        export CLEAN_VERSION=$(echo $VERSION | sed 's/v//g')
        sed -i --regexp-extended 's/(ladybug-grasshopper==).*/ladybug-grasshopper=='"$CLEAN_VERSION"'/' requirements.txt
    - name: "Commit and Push Changes"
      id: push
      env:
        VERSION: ${{ github.event.client_payload.version }}
      run: |
        git config --global user.name 'ladybugbot'
        git config --global user.email 'ladybugbot@users.noreply.github.com'
        git add .
        git commit -m "fix(deps): Bump ladybug-grasshopper to $VERSION"
        git push

  bump_honeybee_grasshopper_core:
    name: "Check Event"
    runs-on: ubuntu-latest
    if: github.event.action == 'honeybee_grasshopper_core_release'
    steps:
    - name: "Checkout Master Branch"
      uses: actions/checkout@v2
      with:
        ref: refs/heads/master
        token: ${{ secrets.DEPS_UPDATING }}
    - name: "Run Update Script"
      env:
        VERSION: ${{ github.event.client_payload.version }}
      run: |
        export CLEAN_VERSION=$(echo $VERSION | sed 's/v//g')
        sed -i --regexp-extended 's/(honeybee-grasshopper-core==).*/honeybee-grasshopper-core=='"$CLEAN_VERSION"'/' requirements.txt
    - name: "Commit and Push Changes"
      id: push
      env:
        VERSION: ${{ github.event.client_payload.version }}
      run: |
        git config --global user.name 'ladybugbot'
        git config --global user.email 'ladybugbot@users.noreply.github.com'
        git add .
        git commit -m "fix(deps): Bump honeybee-grasshopper-core to $VERSION"
        git push

  bump_honeybee_grasshopper_energy:
    name: "Check Event"
    runs-on: ubuntu-latest
    if: github.event.action == 'honeybee_grasshopper_energy_release'
    steps:
    - name: "Checkout Master Branch"
      uses: actions/checkout@v2
      with:
        ref: refs/heads/master
        token: ${{ secrets.DEPS_UPDATING }}
    - name: "Run Update Script"
      env:
        VERSION: ${{ github.event.client_payload.version }}
      run: |
        export CLEAN_VERSION=$(echo $VERSION | sed 's/v//g')
        sed -i --regexp-extended 's/(honeybee-grasshopper-energy==).*/honeybee-grasshopper-energy=='"$CLEAN_VERSION"'/' requirements.txt
    - name: "Commit and Push Changes"
      id: push
      env:
        VERSION: ${{ github.event.client_payload.version }}
      run: |
        git config --global user.name 'ladybugbot'
        git config --global user.email 'ladybugbot@users.noreply.github.com'
        git add .
        git commit -m "fix(deps): Bump honeybee-grasshopper-energy to $VERSION"
        git push

  bump_honeybee_grasshopper_radiance:
    name: "Check Event"
    runs-on: ubuntu-latest
    if: github.event.action == 'honeybee_grasshopper_radiance_release'
    steps:
    - name: "Checkout Master Branch"
      uses: actions/checkout@v2
      with:
        ref: refs/heads/master
        token: ${{ secrets.DEPS_UPDATING }}
    - name: "Run Update Script"
      env:
        VERSION: ${{ github.event.client_payload.version }}
      run: |
        export CLEAN_VERSION=$(echo $VERSION | sed 's/v//g')
        sed -i --regexp-extended 's/(honeybee-grasshopper-radiance==).*/honeybee-grasshopper-radiance=='"$CLEAN_VERSION"'/' requirements.txt
    - name: "Commit and Push Changes"
      id: push
      env:
        VERSION: ${{ github.event.client_payload.version }}
      run: |
        git config --global user.name 'ladybugbot'
        git config --global user.email 'ladybugbot@users.noreply.github.com'
        git add .
        git commit -m "fix(deps): Bump honeybee-grasshopper-radiance to $VERSION"
        git push

  bump_dragonfly_grasshopper:
    name: "Check Event"
    runs-on: ubuntu-latest
    if: github.event.action == 'dragonfly_grasshopper_release'
    steps:
    - name: "Checkout Master Branch"
      uses: actions/checkout@v2
      with:
        ref: refs/heads/master
        token: ${{ secrets.DEPS_UPDATING }}
    - name: "Run Update Script"
      env:
        VERSION: ${{ github.event.client_payload.version }}
      run: |
        export CLEAN_VERSION=$(echo $VERSION | sed 's/v//g')
        sed -i --regexp-extended 's/(dragonfly-grasshopper==).*/dragonfly-grasshopper=='"$CLEAN_VERSION"'/' requirements.txt
    - name: "Commit and Push Changes"
      id: push
      env:
        VERSION: ${{ github.event.client_payload.version }}
      run: |
        git config --global user.name 'ladybugbot'
        git config --global user.email 'ladybugbot@users.noreply.github.com'
        git add .
        git commit -m "fix(deps): Bump dragonfly-grasshopper to $VERSION"
        git push

  bump_lbt_dragonfly:
    name: "Check Event"
    runs-on: ubuntu-latest
    if: github.event.action == 'lbt_dragonfly_release'
    steps:
    - name: "Checkout Master Branch"
      uses: actions/checkout@v2
      with:
        ref: refs/heads/master
        token: ${{ secrets.DEPS_UPDATING }}
    - name: "Run Update Script"
      env:
        VERSION: ${{ github.event.client_payload.version }}
      run: |
        export CLEAN_VERSION=$(echo $VERSION | sed 's/v//g')
        sed -i --regexp-extended 's/(lbt-dragonfly==).*/lbt-dragonfly=='"$CLEAN_VERSION"'/' dev-requirements.txt
    - name: "Commit and Push Changes"
      id: push
      env:
        VERSION: ${{ github.event.client_payload.version }}
      run: |
        git config --global user.name 'ladybugbot'
        git config --global user.email 'ladybugbot@users.noreply.github.com'
        git add .
        git commit -m "chore(deps): Bump lbt-dragonfly to $VERSION"
        git push

  bump_ladybug_rhino:
    name: "Check Event"
    runs-on: ubuntu-latest
    if: github.event.action == 'ladybug_rhino_release'
    steps:
    - name: "Checkout Master Branch"
      uses: actions/checkout@v2
      with:
        ref: refs/heads/master
        token: ${{ secrets.DEPS_UPDATING }}
    - name: "Run Update Script"
      env:
        VERSION: ${{ github.event.client_payload.version }}
      run: |
        export CLEAN_VERSION=$(echo $VERSION | sed 's/v//g')
        sed -i --regexp-extended 's/(ladybug-rhino==).*/ladybug-rhino=='"$CLEAN_VERSION"'/' dev-requirements.txt
    - name: "Commit and Push Changes"
      id: push
      env:
        VERSION: ${{ github.event.client_payload.version }}
      run: |
        git config --global user.name 'ladybugbot'
        git config --global user.email 'ladybugbot@users.noreply.github.com'
        git add .
        git commit -m "chore(deps): Bump ladybug-rhino to $VERSION"
        git push

  bump_lbt_recipes:
    name: "Check Event"
    runs-on: ubuntu-latest
    if: github.event.action == 'lbt_recipes_release'
    steps:
    - name: "Checkout Master Branch"
      uses: actions/checkout@v2
      with:
        ref: refs/heads/master
        token: ${{ secrets.DEPS_UPDATING }}
    - name: "Run Update Script"
      env:
        VERSION: ${{ github.event.client_payload.version }}
      run: |
        export CLEAN_VERSION=$(echo $VERSION | sed 's/v//g')
        sed -i --regexp-extended 's/(lbt-recipes==).*/lbt-recipes=='"$CLEAN_VERSION"'/' dev-requirements.txt
    - name: "Commit and Push Changes"
      id: push
      env:
        VERSION: ${{ github.event.client_payload.version }}
      run: |
        git config --global user.name 'ladybugbot'
        git config --global user.email 'ladybugbot@users.noreply.github.com'
        git add .
        git commit -m "chore(deps): Bump lbt-recipes to $VERSION"
        git push

  bump_honeybee_standards:
    name: "Check Event"
    runs-on: ubuntu-latest
    if: github.event.action == 'honeybee_standards_release'
    steps:
    - name: "Checkout Master Branch"
      uses: actions/checkout@v2
      with:
        ref: refs/heads/master
        token: ${{ secrets.DEPS_UPDATING }}
    - name: "Run Update Script"
      env:
        VERSION: ${{ github.event.client_payload.version }}
      run: |
        export CLEAN_VERSION=$(echo $VERSION | sed 's/v//g')
        sed -i --regexp-extended 's/(honeybee-standards==).*/honeybee-standards=='"$CLEAN_VERSION"'/' dev-requirements.txt
    - name: "Commit and Push Changes"
      id: push
      env:
        VERSION: ${{ github.event.client_payload.version }}
      run: |
        git config --global user.name 'ladybugbot'
        git config --global user.email 'ladybugbot@users.noreply.github.com'
        git add .
        git commit -m "chore(deps): Bump honeybee-standards to $VERSION"
        git push

  bump_honeybee_energy_standards:
    name: "Check Event"
    runs-on: ubuntu-latest
    if: github.event.action == 'honeybee_energy_standards_release'
    steps:
    - name: "Checkout Master Branch"
      uses: actions/checkout@v2
      with:
        ref: refs/heads/master
        token: ${{ secrets.DEPS_UPDATING }}
    - name: "Run Update Script"
      env:
        VERSION: ${{ github.event.client_payload.version }}
      run: |
        export CLEAN_VERSION=$(echo $VERSION | sed 's/v//g')
        sed -i --regexp-extended 's/(honeybee-energy-standards==).*/honeybee-energy-standards=='"$CLEAN_VERSION"'/' dev-requirements.txt
    - name: "Commit and Push Changes"
      id: push
      env:
        VERSION: ${{ github.event.client_payload.version }}
      run: |
        git config --global user.name 'ladybugbot'
        git config --global user.email 'ladybugbot@users.noreply.github.com'
        git add .
        git commit -m "chore(deps): Bump honeybee-energy-standards to $VERSION"
        git push

  bump_ladybug_grasshopper_dotnet:
    name: "Check Event"
    runs-on: ubuntu-latest
    if: github.event.action == 'ladybug_grasshopper_dotnet_release'
    steps:
    - name: "Checkout Master Branch"
      uses: actions/checkout@v2
      with:
        ref: refs/heads/master
        token: ${{ secrets.DEPS_UPDATING }}
    - name: "Run Update Script"
      env:
        VERSION: ${{ github.event.client_payload.version }}
      run: |
        export CLEAN_VERSION=$(echo $VERSION | sed 's/v//g')
        sed -i --regexp-extended 's/(ladybug-grasshopper-dotnet==).*/ladybug-grasshopper-dotnet=='"$CLEAN_VERSION"'/' dev-requirements.txt
    - name: "Commit and Push Changes"
      id: push
      env:
        VERSION: ${{ github.event.client_payload.version }}
      run: |
        git config --global user.name 'ladybugbot'
        git config --global user.email 'ladybugbot@users.noreply.github.com'
        git add .
        git commit -m "chore(deps): Bump ladybug-grasshopper-dotnet to $VERSION"
        git push

  bump_honeybee_openstudio_gem:
    name: "Check Event"
    runs-on: ubuntu-latest
    if: github.event.action == 'honeybee_openstudio_gem_release'
    steps:
    - name: "Checkout Master Branch"
      uses: actions/checkout@v2
      with:
        ref: refs/heads/master
        token: ${{ secrets.DEPS_UPDATING }}
    - name: "Run Update Script"
      env:
        VERSION: ${{ github.event.client_payload.version }}
      run: |
        export CLEAN_VERSION=$(echo $VERSION | sed 's/v//g')
        sed -i --regexp-extended 's/(honeybee-openstudio-gem==).*/honeybee-openstudio-gem=='"$CLEAN_VERSION"'/' ruby-requirements.txt
    - name: "Commit and Push Changes"
      id: push
      env:
        VERSION: ${{ github.event.client_payload.version }}
      run: |
        git config --global user.name 'ladybugbot'
        git config --global user.email 'ladybugbot@users.noreply.github.com'
        git add .
        git commit -m "chore(deps): Bump honeybee-openstudio-gem to $VERSION"
        git push

  bump_lbt_measures:
    name: "Check Event"
    runs-on: ubuntu-latest
    if: github.event.action == 'lbt_measures_release'
    steps:
    - name: "Checkout Master Branch"
      uses: actions/checkout@v2
      with:
        ref: refs/heads/master
        token: ${{ secrets.DEPS_UPDATING }}
    - name: "Run Update Script"
      env:
        VERSION: ${{ github.event.client_payload.version }}
      run: |
        export CLEAN_VERSION=$(echo $VERSION | sed 's/v//g')
        sed -i --regexp-extended 's/(lbt-measures==).*/lbt-measures=='"$CLEAN_VERSION"'/' ruby-requirements.txt
    - name: "Commit and Push Changes"
      id: push
      env:
        VERSION: ${{ github.event.client_payload.version }}
      run: |
        git config --global user.name 'ladybugbot'
        git config --global user.email 'ladybugbot@users.noreply.github.com'
        git add .
        git commit -m "chore(deps): Bump lbt-measures to $VERSION"
        git push
